# Generated by Django 5.1.2 on 2024-10-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_mime_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('file_last_modified', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=66)),
                ('transaction_hash', models.CharField(default='', max_length=256)),
                ('transaction_created_at', models.DateTimeField(auto_now=True)),
                ('has_proof', models.BooleanField()),
            ],
        ),
    ]
